sudo: false
language: python

git:
  depth: 3

python:
  - "3.3"

install:
  - pip install flake8
  - pip install pydocstyle

script:
  - flake8 . --max-line-length=120
  - pydocstyle . --add-ignore=D202

notifications:
  email:
    on_success: never
    on_failure: always
